import Head from 'next/head';
import Image from 'next/image';
import {
  BeakerIcon,
  BellIcon,
  SearchIcon,
  ShoppingBagIcon,
} from '@heroicons/react/solid';

export default function Home() {
  return (
    <>
      <Head>
        <title>Online - topup</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='w-full lg:w-[480px] mx-auto min-h-screen h-full bg-base-200'>
        <header className='flex flex-col relative h-60 w-full justify-center gap-4'>
          <div className='block absolute bg-accent h-full w-full top-0 rounded-b-3xl'></div>
          <div className='relative flex flex-row items-center gap-2 w-full justify-center'>
            <ShoppingBagIcon className='h-10 w-10 text-primary' />
            <p>My Shop</p>
          </div>
          <div className='relative form-control items-center mb-12'>
            <div className='input-group mx-auto px-8'>
              <span>
                <SearchIcon className='w-4 h-4' />
              </span>
              <input
                type='text'
                placeholder='Cari Mobile Legends ...'
                className='input input-bordered w-full text-black placeholder:text-slate-700'
              />
            </div>
          </div>
        </header>
        <section className='p-6'>
          <h5 className='mb-6 text-xl font-bold'>Rekomendasi!</h5>
          <div>
            <div className='w-32 min-h-32 bg-base-100 rounded-lg z-10 p-4 shadow-md'>
              <div className='relative rounded-lg after:bg-[url(https://api.menorigaming.com/media/photo_2022-05-04_08-42-20-10a10e.jpg)] after:top-[10px] after:left-0 after:right-0 after:absolute after:w-16 after:h-16 after:-z-10 after:mx-auto after:blur-lg z-10 mt-[-1.8rem]'>
                <div className='flex items-center justify-center z-10'>
                  <Image
                    src='https://api.menorigaming.com/media/photo_2022-05-04_08-42-20-10a10e.jpg'
                    alt='some img'
                    height={64}
                    width={64}
                    placeholder='empty'
                    className='rounded-lg'
                  />
                </div>
              </div>
              <div className='flex flex-col items-center mt-4'>
                <h5 className='text-base font-medium'>Moontoon</h5>
                <p className='text-xs'>Mobile Legends</p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
